<?php

namespace tecnocen\roa\behaviors;

use yii\helpers\Url;
use yii\web\Link;

/**
 * Behavior to autogenerate curies links.
 *
 * @author Angel (Faryshta) Guevara <aguevara@alquimiadigital.mx>
 */
class Curies extends \yii\base\Behavior
{
    /**
     * @var Link[] The curies links. Autogenerated links will be stored here.
     */
    public $curiesLinks = [];

    /**
     * @var string? name of the autogenerated expand curie. Set null if you
     * don't want to autogenerate expand curie.
     */
    public $expandCurieName = 'expand';

    /**
     * @var array the configuration used to generate the expand curie.
     */
    public $expandCurieLink = [
        'title' => 'Embeddable related resources.',
    ];

    /**
     * Return all the curies and related links.
     *
     * @return array the configured and autogenerated curies and related links.
     */
    public function getCuriesLinks()
    {
        if ($this->expandCurieName) {
            $this->curiesLinks['curies'][] = new Link(array_merge(
                $this->expandCurieLink,
                [
                    'name' => $this->expandCurieName,
                    'href' => $this->owner->getSelfLink()
                        . "?{$this->expandCurieName}={rel}",
                ]
            ));

            foreach ($this->owner->extraFields() as $field => $value) {
                if (is_int($field)) {
                    $field = $value;
                }

                $this->curiesLinks["{$this->expandCurieName}:$field"] = $field;
            }
        }

        return $this->curiesLinks;
    }
}
